#!/usr/bin/env python

# A brainfuck interpreter, written in python

import sys

if len(sys.argv) == 1:
    print "ERROR: Expected an argument."
    sys.exit(1)
else:
    source = sys.argv[1]
    try:
        f = open(source,"r")
        code = f.read()
        f.close()
    except IOError:
        code = sys.argv[1]

# Brainfuck's tape is theoretically infinite; in this case, it is a
# 30,000-cell loop
tape = [0 for x in xrange(0,30000)]
cell = 0; inputcell = 0
if len(sys.argv) > 2:
    input = sys.argv[2]

x = 0
while x < len(code):
    if code[x] == "+":
        tape[cell] += 1
    elif code[x] == "-":
        tape[cell] -= 1
    elif code[x] == ">":
        cell +=1
    elif code[x] == "<":
        cell -= 1
    elif code[x] == "[":
        if tape[cell] == 0:
            looplevel = 1
            while looplevel > 0:
                x += 1
                if code[x] == "[":
                    looplevel += 1
                elif code[x] == "]":
                    looplevel -= 1
    elif code[x] == "]":
        if tape[cell] != 0:
            looplevel = 1
            while looplevel > 0:
                x -= 1
                if code[x] == "[":
                    looplevel -= 1
                elif code[x] == "]":
                    looplevel += 1
    elif code[x] == ".":
        sys.stdout.write(chr(tape[cell]))
    elif code[x] == ",":
        if inputcell < len(input):
            tape[cell] = ord(input[inputcell])
        inputcell += 1
    else:
        pass
    x += 1
